export const doorValues = {
  id: 0,
  verk_nr: "",
  customer: "",
  seller: "",
  nafn_hurdar: "",
  height: "",
  width: "",
  vegg_tykkt: "",
  tegund: "",
  tykkt: "",
  efni_hurd: "",
  efni_karmur: "",
  kantliming_hurd: "",
  kantliming_karmur: "",
  vinstri: false,
  haegri: false,
  felli_throskuldur: false,
  gluggi: false,
  throskuldur: false,
  gerreti: false,
  athugasemd: "",
  annad: "",
  lamir: "",
  skra: "",
  slaglisti: "",
  parket: "",
  flisar: "",
  gluggi_width: "",
  gluggi_height: "",
  gluggi_fra_botni: "",
  gluggi_fra_toppi: "",
  gluggi_fra_vinstri: "",
  gluggi_fra_hægri: "",
  geretti_tykkt: 9,
  geretti_breidd: 70,

  karmþykkt: 28,
  bil_vid_golf: 10,
  rymi_utan_karms: 12,
};

export const fdcValues = {
  width: "",
  height: "",
  depth: "",
  carcase_color: "",
  edge_color: "",
  shelf_color: "",
  door_color: "",
  shelf_count: "",
  shelf_depth: "",
  door_count: "",
  thickness: "",
  customer: "",
  seller: "",
  carcase_nobilia: false,
  carcase_change_gks: false,
  self_nobila: false,
  self_change_gks: false,
  doors_nobila: false,
  doors_change_gks: false,
  light_Shelf: false,
  Athugasemd1: "",
  Athugasemd2: "",
};
